// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdgKl1tsZmKSoN1sHOZfpPsYM6uy1vN3k',
    appId: '1:944601640368:web:8491d5abc8c050109cfa75',
    messagingSenderId: '944601640368',
    projectId: 'waterledger-e7544',
    authDomain: 'waterledger-e7544.firebaseapp.com',
    storageBucket: 'waterledger-e7544.firebasestorage.app',
    measurementId: 'G-73LMSNZG7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjCYwo1bUxDzwNaDqf1HC1T3sA0nAIS4',
    appId: '1:944601640368:android:8f2db57c61fcc4279cfa75',
    messagingSenderId: '944601640368',
    projectId: 'waterledger-e7544',
    storageBucket: 'waterledger-e7544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq3WGq14mo-aLfCyXtSmki8Cig5pY9wM0',
    appId: '1:944601640368:ios:540c5d42d982887c9cfa75',
    messagingSenderId: '944601640368',
    projectId: 'waterledger-e7544',
    storageBucket: 'waterledger-e7544.firebasestorage.app',
    iosBundleId: 'com.example.waterLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq3WGq14mo-aLfCyXtSmki8Cig5pY9wM0',
    appId: '1:944601640368:ios:540c5d42d982887c9cfa75',
    messagingSenderId: '944601640368',
    projectId: 'waterledger-e7544',
    storageBucket: 'waterledger-e7544.firebasestorage.app',
    iosBundleId: 'com.example.waterLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdgKl1tsZmKSoN1sHOZfpPsYM6uy1vN3k',
    appId: '1:944601640368:web:4efaff7cbfe155a39cfa75',
    messagingSenderId: '944601640368',
    projectId: 'waterledger-e7544',
    authDomain: 'waterledger-e7544.firebaseapp.com',
    storageBucket: 'waterledger-e7544.firebasestorage.app',
    measurementId: 'G-NDT69EKL5Q',
  );
}
